Add exportdata compressed sql file to GDrive
Added shell commands to archive and sync (ie, upload) the .sql
output of the migratedata script.
This will put a compressed version of our most up-to-date
cleaned data file into a shared Google Drive folder (owned by the
digitalmarketplace-ci@digitalcabinet-office.gov.uk account).

No historical data will be preserved.  Only the most recent dump
is uploaded (overwriting what was there previously), and the local
version is removed once the sync is complete.

diff --git a/job_definitions/migratedata.yml b/job_definitions/migratedata.yml
--- a/job_definitions/migratedata.yml
+++ b/job_definitions/migratedata.yml
@@ -33,10 +33,34 @@
           . ./venv/bin/activate
           pip install -e .
 
+          EXPORTDATA_PATH='./dumps/sql/exportdata.sql'
+
           AWS_PROFILE="production" dmaws migratedata production  \
-            $TARGET_STAGE $TARGET_STAGE \
+            $TARGET_STAGE $TARGET_STAGE $EXPORTDATA_PATH \
             ~/digitalmarketplace-credentials/dmaws-vars-files/$TARGET_STAGE.yml \
             -f ~/digitalmarketplace-credentials/dmaws-vars-files/production.yml
+
+          # we expect this file to be there after running migratedata
+          if ! [ -f "$EXPORTDATA_PATH" ];then
+              rm -r ./dumps
+
+              echo "Exiting: can't find the $EXPORTDATA_PATH file." >&2
+              exit 1
+          fi
+
+          echo "Found $EXPORTDATA_PATH. Archiving..." >&2
+          zip ./dumps/sql/exportdata.zip $EXPORTDATA_PATH
+
+          echo "Removing $EXPORTDATA_PATH." >&2
+          rm $EXPORTDATA_PATH
+
+          # "0B9HQ_eYjd1zjWm9DaEpNUzZhRzg" is the id of the "/dumps" Google Drive folder
+          echo "Sync local file with GDrive sync folder." >&2
+          /usr/local/bin/gdrive --config "/var/lib/jenkins/.gdrive" sync upload --delete-extraneous ./dumps/sql 0B9HQ_eYjd1zjWm9DaEpNUzZhRzg
+
+          echo "Removing local ./dumps directory." >&2
+          rm -r ./dumps
+          exit 0
     publishers:
       - trigger-parameterized-builds:
           - project: notify-slack
